//! Bundled city road network loader (Step 6).
//!
//! Roads are stored as compact JSON polylines, one file per city,
//! under `crates/tui/data/cities/<slug>.json`:
//!
//! ```json
//! {
//!   "name": "Seattle",
//!   "bbox": [min_lat, min_lon, max_lat, max_lon],
//!   "roads": [
//!     { "importance": "motorway", "points": [[lat, lon], ...] },
//!     ...
//!   ]
//! }
//! ```
//!
//! Generated by `scripts/fetch_city_roads.py` from a one-shot Overpass
//! query. Bundled so users don't pay the Overpass rate-limit cost on
//! every launch and so the city screen works fully offline.
//!
//! Step 6 loads the bundled JSON via `include_str!` at compile time
//! and exposes three helpers used by the renderer (Step 7):
//!   * `CityRoads::load_bundled(slug)` → parse one bundled city.
//!   * `CityRoads::location()` → derive a `CityLocation` from the
//!     bbox so the renderer has a uniform `(name, lat, lon, bbox)`.
///   * `CityRoads::group_by_importance()` → bucket polylines by
///     importance tag so the renderer can paint arterial / residential
///     / footway at different stroke widths.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// Re-export the canonical `CityLocation` from `cyberdeck-core`.
/// `CityRoads::location` builds one out of the bundled bbox so the
/// renderer has a uniform source of `(name, lat, lon, bbox)`.
pub use cyberdeck_core::city::CityLocation;

/// A road segment as a polyline of `[lat, lon]` pairs (WGS84).
/// `importance` is a coarse tag from the Overpass query
/// (`motorway`, `trunk`, `primary`, `secondary`, `residential`,
/// `footway`) that the traffic overlay uses to weight its colour.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RoadImportance(pub String);

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Polyline {
    pub points: Vec<[f64; 2]>,
    pub importance: RoadImportance,
}

/// Top-level document deserialized from a bundled `cities/<slug>.json`.
/// Kept distinct from `cyberdeck_core::city::CityLocation` because the
/// bundled file is the authoritative source of road geometry and the
/// renderer reads this directly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CityRoads {
    pub name: String,
    /// `[min_lat, min_lon, max_lat, max_lon]` — matches the OSM
    /// `bounding-box` order.
    pub bbox: [f64; 4],
    pub roads: Vec<Polyline>,
}

impl CityRoads {
    /// All bundled cities (kebab-case slugs). Used by the City
    /// screen's `p` picker and by tests below.
    pub const BUNDLED: &'static [&'static str] = &[
        "seattle",
        // The remaining four slots will populate as the matching
        // JSON files are added by `scripts/fetch_city_roads.py`. The
        // renderer / picker gracefully fall back to "seattle" if a
        // slug isn't bundled yet (see `load_bundled_or_default`).
        "london",
        "tokyo",
        "berlin",
        "nyc",
    ];

    /// Load a bundled city by slug. Unknown slugs (or any of the
    /// not-yet-bundled slugs above) return `None` so the caller can
    /// fall back without panicking.
    ///
    /// The data is `include_str!`'d at compile time — one file read
    /// per bundled slug, total binary cost ≈ a few hundred KB. We
    /// always include `seattle.json` (it's tiny and useful as a
    /// test + offline-default); the others land as their JSON files
    /// are committed.
    pub fn load_bundled(slug: &str) -> Option<Self> {
        // `include_str!` resolves relative to the source file
        // (`crates/tui/src/screens/city/roads.rs`), so we walk up two
        // levels to reach `crates/tui/data/cities/<slug>.json`.
        let raw = match slug {
            "seattle" => include_str!("../../../data/cities/seattle.json"),
            // Future bundled cities land here. Returning the
            // `unimplemented!` panic was the old Step 5 stub; we now
            // return None so the UI can degrade cleanly until the
            // file is added.
            _ => return None,
        };
        serde_json::from_str(raw)
            .map_err(|e| {
                // Surface to logs but return None so the UI shows
                // "no bundled data for <slug>" rather than crashing
                // in the render loop.
                tracing::warn!("bundled city {slug} JSON failed to parse: {e}");
                e
            })
            .ok()
    }

    /// Resolve a slug to bundled data, falling back to `seattle` if
    /// the requested slug isn't available. The City-screen picker
    /// calls this so users can cycle through slugs that aren't all
    /// bundled yet.
    pub fn load_bundled_or_default(slug: &str) -> (String, Self) {
        if let Some(cr) = Self::load_bundled(slug) {
            return (slug.to_string(), cr);
        }
        // Fallback to seattle; if seattle itself is missing (it
        // shouldn't be), we panic — that'd be a build-time mistake.
        let cr = Self::load_bundled("seattle")
            .expect("seattle.json must be bundled — checked into the repo");
        ("seattle".to_string(), cr)
    }

    /// Convenience: derive the bundled-bbox-shaped `CityLocation`.
    /// Used when the IP geolocator doesn't return a bbox (it never
    /// does on the free tier) and the renderer needs a viewport.
    pub fn location(&self) -> CityLocation {
        let [min_lat, min_lon, max_lat, max_lon] = self.bbox;
        CityLocation {
            name: self.name.clone(),
            country: String::new(),
            country_code: String::new(),
            region: String::new(),
            lat: (min_lat + max_lat) / 2.0,
            lon: (min_lon + max_lon) / 2.0,
            bbox: Some(self.bbox),
            timezone: String::new(),
        }
    }

    /// Group polylines by importance. Uses `BTreeMap` so the keys
    /// iterate in a stable, alphabetical order — the renderer
    /// paints arterials on top of residentials and that ordering is
    /// reproducible across launches.
    pub fn group_by_importance(&self) -> BTreeMap<&'static str, Vec<&Polyline>> {
        let mut out: BTreeMap<&'static str, Vec<&Polyline>> = BTreeMap::new();
        for r in &self.roads {
            // Bucket by first-seen literal. The renderer only cares
            // about a small fixed set of keys; for diagnostics we
            // store arbitrary strings under their raw tag so an
            // unrecognised importance (e.g. "service") still shows
            // up grouped.
            let key: &'static str = match r.importance.0.as_str() {
                "motorway" | "trunk" | "primary" | "secondary" | "residential" | "footway" => {
                    // Box the string slice so the `&'static str`
                    // type bound holds for the common case.
                    Box::leak(r.importance.0.clone().into_boxed_str())
                }
                _ => "other",
            };
            out.entry(key).or_default().push(r);
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Bundled `seattle.json` round-trips, has 6 polylines spanning
    /// all 6 expected importance tags.
    #[test]
    fn bundled_seattle_parses_and_groups() {
        let cr = CityRoads::load_bundled("seattle").expect("seattle.json is bundled");
        assert_eq!(cr.name, "Seattle");
        assert_eq!(cr.bbox.len(), 4);
        assert_eq!(cr.roads.len(), 6);

        let groups = cr.group_by_importance();
        // Every tagged bucket we put in the fixture must show up;
        // BTreeMap keys iterate alphabetically.
        let keys: Vec<&&str> = groups.keys().collect();
        assert!(
            keys.iter().any(|k| **k == "motorway"),
            "motorway group missing: {keys:?}"
        );
        assert!(groups["footway"].len() >= 1);
    }

    /// Slugs not on the bundled-file list return `None` cleanly;
    /// the picker falls back to seattle.
    #[test]
    fn unknown_slug_returns_none_and_falls_back() {
        assert!(CityRoads::load_bundled("atlantis").is_none());
        let (used_slug, cr) = CityRoads::load_bundled_or_default("atlantis");
        assert_eq!(used_slug, "seattle");
        assert_eq!(cr.name, "Seattle");
    }

    /// `location()` projects the bbox centre correctly.
    #[test]
    fn location_uses_bbox_center() {
        let cr = CityRoads::load_bundled("seattle").unwrap();
        let loc = cr.location();
        let [min_lat, min_lon, max_lat, max_lon] = cr.bbox;
        assert!((loc.lat - (min_lat + max_lat) / 2.0).abs() < 1e-9);
        assert!((loc.lon - (min_lon + max_lon) / 2.0).abs() < 1e-9);
        assert_eq!(loc.bbox, Some(cr.bbox));
        assert_eq!(loc.name, cr.name);
    }

    /// `BUNDLED` slug list contains `seattle` (so the offline
    /// fallback in `load_bundled_or_default` is always reachable).
    #[test]
    fn bundled_contains_seattle_offline_default() {
        assert!(CityRoads::BUNDLED.contains(&"seattle"));
    }

    /// Polyline points are stored as `[lat, lon]` in WGS84; verify
    /// the first point of `motorway` line is within the bbox (so we
    /// don't render off-screen by accident).
    #[test]
    fn bundled_roads_reside_inside_their_bbox() {
        let cr = CityRoads::load_bundled("seattle").unwrap();
        let [min_lat, min_lon, max_lat, max_lon] = cr.bbox;
        for r in &cr.roads {
            for [lat, lon] in &r.points {
                assert!(
                    *lat >= min_lat && *lat <= max_lat,
                    "point {lat},{lon} of {:?} lies outside lat bbox [{min_lat},{max_lat}]",
                    r.importance
                );
                assert!(
                    *lon >= min_lon && *lon <= max_lon,
                    "point {lat},{lon} of {:?} lies outside lon bbox [{min_lon},{max_lon}]",
                    r.importance
                );
            }
        }
    }
}
